name: Preview

on:
  pull_request:
    branches:
      - 'v[0-9]+'

jobs:
  publish-previews:
    name: Publish Preview Packages
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org
    - name: Publish PR Preview
      uses: thefrontside/actions/publish-pr-preview@v2
      env:
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
